/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shanpin' at '17-4-10 上午11:36' with Gradle 2.5
 *
 * @author shanpin, @date 17-4-10 上午11:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
